{% set name = "mosdef-gomc" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GOMC-WSU/MoSDeF-GOMC/archive/{{ version }}.tar.gz
  sha256: 0ede0fc2d7e6a92165472925cff4f8cd4c39b96a6273f825b82b28b331382b85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<=3.10
    - pip
  run:
    - python >=3.9,<=3.10
    - garnett
    - gsd
    - pycifrw
    - sympy
    - symengine
    - python-symengine
    - forcefield-utilities >=0.2.1
    - foyer >=0.11.3
    - gmso >=0.9.1
    - mbuild >=0.16.0

test:
  imports:
    - mosdef_gomc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/GOMC-WSU/MoSDeF-GOMC
  summary: A User-Friendly Python Interface for Creating All of the files required to run a GPU Optimized Monte Carlo (GOMC) simulation engine via the Molecular Simulation Design Framework (MoSDeF) software.
  description: |
    A User-Friendly Python Interface for Creating All of the files required to run a GPU Optimized Monte Carlo (GOMC) simulation engine via the Molecular Simulation Design Framework (MoSDeF) software.
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  doc_url: https://github.com/GOMC-WSU/MoSDeF-GOMC
  dev_url: https://github.com/GOMC-WSU/MoSDeF-GOMC

extra:
  recipe-maintainers:
    - umesh-timalsina
    - bc118
