{% set name = "mosdef-gomc" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GOMC-WSU/MoSDeF-GOMC/archive/{{ version }}.tar.gz
  sha256: 88ad1ec8e30930c4db2276f3c748c700d25e129450a35049da9d7847b506f49d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<=3.11
    - pip
  run:
    - python >=3.10,<=3.11
    - garnett
    - gsd
    - pycifrw
    - sympy
    - symengine
    - python-symengine
    - forcefield-utilities >=0.3.0
    - foyer >=0.12.1
    - gmso >=0.12.1
    - mbuild >=0.17.0

test:
  imports:
    - mosdef_gomc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/GOMC-WSU/MoSDeF-GOMC
  summary: A User-Friendly Python Interface for Creating All of the files required to run a GPU Optimized Monte Carlo (GOMC) simulation engine via the Molecular Simulation Design Framework (MoSDeF) software.
  description: |
    A User-Friendly Python Interface for Creating All of the files required to run a GPU Optimized Monte Carlo (GOMC) simulation engine via the Molecular Simulation Design Framework (MoSDeF) software.
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  doc_url: https://github.com/GOMC-WSU/MoSDeF-GOMC
  dev_url: https://github.com/GOMC-WSU/MoSDeF-GOMC

extra:
  recipe-maintainers:
    - umesh-timalsina
    - bc118
